site_name: Flask-Admin CLI
site_url: https://mariofix.github.io/flask-admin-cli
repo_url: https://github.com/mariofix/flask-admin-cli
repo_name: mariofix/flask-admin-cli
site_description: Flask-Admin CLI documentation
site_author: mariofix <yo@mariofix.com>
copyright: "&copy;2023 - Mario Hernández"
edit_uri: ""

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tracking
    - navigation.top
    - header.autohide

plugins:
  - mkdocstrings

nav:
  - index.md

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

